---
title: "enrollment report"
author: "Luran M."
date: "July 10, 2019"
output: html_document
---
```{r echo=FALSE, results="hide", include=F}
library(knitr, warn.conflicts = F, quietly = T)
library(tidyr, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(keyringr, warn.conflicts = F, quietly = T)
library(redcapAPI, warn.conflicts = F, quietly = T)
library(REDCapR, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)
#Create path to and api link to RedCaps
# # https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
credential_label <- "beach_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)
# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)
# crc variables
#fields <- exportFieldNames(rcon)
#crc variables for 3rd trimester visit
desired_fields_enroll=c("mom2wk_mod","mom3t_prepreg_bmi","inf2wk_delivery_location","mom3t_delivery_location","beach_consent_date1")
# combine desired fields and import test_id and redcap_event_name
desired_fields_all=c(desired_fields_enroll,"test_id","redcap_event_name")
# events to retain
#exportEvents(rcon)
events_to_retain  <- c("third_trimester_arm_1", "two_week_arm_1", "two_month_arm_1")
# list of instruments
#exportInstruments(rcon)
Instruments_to_retain <- c("health_update_3rd_trimester_v5082518","clinical_health_update_2wk_v4_042218",
                           "clinical_health_update_2mo_to_12mo_v3_022118","infant_feeding_questionnaire_2_weeks_v3_042218",
                           "infant_feeding_questionnaire_2mo_to_12mo_v3_022118")
# list of events
#exportEvents(rcon)
# list records
#exportRecords(rcon)
# export field names
#exportFieldNames(rcon)
# consented records
consent.records.v1=c("BLS001A")
# pull data
ds_some_rows_v1 <- redcap_read(
  batch_size=300,
  records= consent.records.v1,
  redcap_uri = uri, 
  token      = beach_token, 
  fields     = desired_fields_all,
  events     = events_to_retain,
  )$data
head(ds_some_rows_v1)
```


##Mode of delivery for participant:

```{r echo=FALSE}
mode_delevery<-ds_some_rows_v1%>%
  select(test_id, mom2wk_mod,redcap_event_name)%>%
  filter(redcap_event_name=="two_week_arm_1")%>%
  rename("participant"=test_id,"Mode of Delivery"=mom2wk_mod)%>%
  select(participant,"Mode of Delivery")
for(i in 1:nrow(mode_delivery)){
  cat(mode_delivery[i,1])
  if(is.na(mode_delivery[i,2]))
    cat("\tDid not respond as to mode of delivery\n")
  else if(mode_delivery[i,2]==1)
    cat("\tDelivered : Vaginaly\n")
  else if(mode_delivery[i,2]==2)
    cat("\tDelivered : Cesarean\n")
}

```

##Pre-pregnant BMI of participant:
```{r echo=FALSE}
BMI <- ds_some_rows_v1%>%
  select(test_id,mom3t_prepreg_bmi)%>%
  filter(test_id%in%apple)%>%
  rename("participant"=test_id,"pre-Pregnant BMI"=mom3t_prepreg_bmi)
kable(BMI)
```

##Delivery Location of dropped participants:
###If empty, then dropped participant didn't provide location
```{r echo=FALSE}
#chart of Delivery location question at 3rd trimester   
DeliveryLocation_tri <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,mom3t_delivery_location)%>%
  arrange(test_id,redcap_event_name)%>%
  filter(redcap_event_name == "third_trimester_arm_1")%>%
  select(test_id,mom3t_delivery_location)
for(i in 1:nrow(DeliveryLocation_tri)){
  cat(DeliveryLocation_tri[i,1])
  if(is.na(DeliveryLocation_tri[i,2]))
    cat("\tDid not respond\n")
  else if(DeliveryLocation_tri[i,2]==1)
    cat("\tPlanning to Delivered in UF/Shands\n")
  else if(DeliveryLocation_tri[i,2]==2)
    cat("\tPlanning to Deliver in North Florida Regional\n")
  else if(DeliveryLocation_tri[i,2]==3)
    cat("\tPlanning to Deliver in Birth and Wellness Center of Gainesville\n")
  else if(DeliveryLocation_tri[i,2]==4){
    cat("\tPlanning to Deliver in North Florida Regional\n")
}
  else if(DeliveryLocation_tri[i,2]==5)
    cat("\tResponded that they don't know where they will Deliver\n")
}
```

```{r, echo=FALSE}
#chart of Delivery location question at 2 week
DeliveryLocation_wk <-ds_some_rows_v1%>%
  select(test_id,redcap_event_name,inf2wk_delivery_location___1:inf2wk_delivery_location___5)%>%
  arrange(test_id,redcap_event_name)%>%
  rename("UFHealth"=inf2wk_delivery_location___1,
         "North Florida Regional"=inf2wk_delivery_location___2,
         "Birth & wellness Center of Gainesville"=inf2wk_delivery_location___3,
         "other"=inf2wk_delivery_location___4,
         "IDK"=inf2wk_delivery_location___5)%>%
  filter(redcap_event_name == "two_week_arm_1")%>%
  rename(participant=test_id,"visit type"=redcap_event_name)
#seperate variables and check for population 
for(i in 1:nrow(DeliveryLocation_wk)){
  cat(DeliveryLocation_wk[i,1])
  if(DeliveryLocation_wk[i,3]>0)
    cat("\tDelivered in  UF\n")  
  else if(DeliveryLocation_wk[i,4]>0)
    cat("\tDelivered in  North Florida\n")  
  else if(DeliveryLocation_wk[i,5]>0)
    cat("\tDelivered in Gainesville Birth and Wellness Center\n")  
  else if(DeliveryLocation_wk[i,6]>0){
    cat("\t Delivered in other\n")
  }
  else if(DeliveryLocation_wk[i,7]>0)
    cat("\tDoes not know location of delivery\n")  
  else
    cat("\tParticipant Didn't respond in questionare\n")    
}
```

##Month of participant enrollment 
```{r echo=FALSE}
```
