---
title: "Missing_infoV2"
author: "Luran M."
date: "June 18, 2019"
output: html_document
---


```{r echo=FALSE, results="hide", include=F}

library(knitr, warn.conflicts = F, quietly = T)
library(tidyr, warn.conflicts = F, quietly = T)
library(dplyr, warn.conflicts = F, quietly = T)
library(ggplot2, warn.conflicts = F, quietly = T)
library(keyringr, warn.conflicts = F, quietly = T)
library(redcapAPI, warn.conflicts = F, quietly = T)
library(REDCapR, warn.conflicts = F, quietly = T)
library(lubridate, warn.conflicts = F, quietly = T)

#Create path to and api link to RedCaps
# # https://cran.r-project.org/web/packages/keyringr/vignettes/Avoiding_plain_text_passwords_in_R_with_keyringr.html
credential_label <- "beach_api"
credential_path <- paste(Sys.getenv("USERPROFILE"), '\\DPAPI\\passwords\\', Sys.info()["nodename"], '\\', credential_label, '.txt', sep="")
uri <- "https://redcap.ctsi.ufl.edu/redcap/api/"
beach_token<-decrypt_dpapi_pw(credential_path)

# Create connections
rcon <- redcapConnection(url=uri, token=beach_token)


#crc variables for 3rd trimester visit
desired_fields_triHU1=c("mom3t_bio_child",
                        "mom3t_hispanic",
                        "mom3t_baby_sex",
                        "mom3t_baby_hispanic",
                        "mom3t_delivery_location",
                        "mom3t_infant_care")
# crc variables for the 2 week visit 
desired_fields_2wkHU=c("inf2wk_delivery_location",
                       "inf2wk_pediatric_care",
                       "mom2wk_healthcare_service",
                       "inf2wk_sex",
                       "mom2wk_baby_weight_pounds",
                       "mom2wk_baby_ounces",
                       "mom2wk_wt_lb_2",
                       "inf2wk_baby_weight_today",
                       "inf2wk_abx_length")
#crc variables for the 2 month visit 
desired_fields_2moHU=c("inf2mo_infant_weight",
                       "inf2mo_infant_length",
                       "inf2mo_infant_length_2",
                       "inf2mo_baby_recieve_care",
                       "inf2mo_healthcare_services")

# combine desired fields and import test_id and redcap_event_name
desired_fields_all=c(desired_fields_triHU1,desired_fields_2wkHU,desired_fields_2moHU,"test_id","redcap_event_name")

# events to retain
events_to_retain  <- c("third_trimester_arm_1", "two_week_arm_1", "two_month_arm_1")

# list of instruments

# consented records
consent.records.v1=c("BLS045A")

# pull data
ds_some_rows_v1 <- redcap_read(
  batch_size=300,
  records= consent.records.v1,
  redcap_uri = uri, 
  token      = beach_token, 
  fields     = desired_fields_all,
  events     = events_to_retain,
  )$data

```
##Participants that will be looked at:
```{r echo=FALSE}
cat(ds_some_rows_v1[1,1])
```

##Questions not responded by participant in 3rd Trimester questionare:

---------------------------------------------------
```{r echo=FALSE}
third <- ds_some_rows_v1%>%
  select(desired_fields_triHU1,redcap_event_name,test_id)%>%
  filter(redcap_event_name=="third_trimester_arm_1")
cat(third[1,8])
if(is.na(third[1,5]))
  cat("\nparticipant didn't tell delivery location")

if(is.na(third[1,6]))
  cat("\nparticipant didn't disclose location of pediatric care")

if(is.na(third[1,4]))
  cat("\nparticipant didn't respond if the child was hispanic")

if(is.na(third[1,3]))
  cat("\nparticipant didn't disclose child sex")

if(is.na(third[1,1]))
  cat("\nparticipant didn't disclose child sex 1")

```

## Questions not responded by participant in 2-week quetionare:

---------------------------------------------------
```{r echo=FALSE}
simple_pull=c( "inf2wk_sex",
               "mom2wk_baby_weight_pounds",
               "mom2wk_baby_ounces",
               "mom2wk_wt_lb_2",
               "inf2wk_baby_weight_today",
               "inf2wk_abx_length",
               "redcap_event_name",
               "test_id")
#does not pull inf2wk_healthcare_servies
wk <- ds_some_rows_v1%>%
  select(simple_pull,inf2wk_delivery_location___1:inf2wk_delivery_location___5,inf2wk_pediatric_care___1:inf2wk_pediatric_care___5)%>%
  filter(redcap_event_name=="two_week_arm_1")

cat(wk[1,8])

if(is.na(wk[1,1]))
  cat("\nParticipant didn't respond to infant sex")
if(is.na(wk[1,2]))
  cat("\nParticipant didn't respond to infant birth weight(Ib)")
if(is.na(wk[1,3]))
  cat("\nParticipant didn't respond to infant birth weight(ounces)")
if(is.na(wk[1,4]))
  cat("\nParticipant didn't respond to infant birth length")
if(is.na(wk[1,5]))
  cat("\nparticipant didn't respond to baby weight on day of visit")
if(is.na(wk[1,6]))
  cat("\nParticiapnt didn't respond to baby length on day of visit")
count=0
for(i in 9:13)
  if(is.na(wk[1,i]))
    count=count+1
if(count==0)
  cat("\nParticipant didn't respond to delivery location")
count=0
for(i in 14:18)
  if(is.na(wk[1,i]))
    count=count+1
if(count==0)
  cat("\nParticipant didn't respond to where they recive pediatric care")
```


##Questions not responded by participant in 2 month Questionare:

---------------------------------------------------

```{r echo=FALSE}
#does not pull inf2mo_healthcare_services
mo <- ds_some_rows_v1%>%
  select(test_id,redcap_event_name,inf2mo_infant_weight,inf2mo_infant_length,inf2mo_infant_length_2,inf2mo_baby_recieve_care___1:inf2mo_baby_recieve_care___5)%>%
  filter(redcap_event_name=="two_month_arm_1")


cat(mo[1,1])
if(is.na(wk[1,3]))
  cat("\nParticipant didn't respond to infant birth weight(Ib)")
if(is.na(wk[1,4]))
  cat("\nParticipant didn't respond to infant birth length")
if(is.na(wk[1,5]))
  cat("\nParticipant didn't respond to infant birth length 2")
count=0
for(i in 6:10)
  if(is.na(wk[1,i]))
    count=count+1
if(count==0)
  cat("\nParticipant didn't respond to where they recive pediatric care")
```